In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [59]:
dataset = pd.read_csv("../aclImdb/train.csv")

In [100]:
# To see what does the dataset looks like
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    25000 non-null  object
 1   score   25000 non-null  int64 
 2   label   25000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 586.1+ KB


In [101]:
dataset['score'].value_counts()

1     5100
10    4732
8     3009
4     2696
7     2496
3     2420
2     2284
9     2263
Name: score, dtype: int64

In [102]:
review = dataset['text'].loc[2]
review

"Lars Von Trier is never backward in trying out new techniques. Some of them are very original while others are best forgotten.<br /><br />He depicts postwar Germany as a nightmarish train journey. With so many cities lying in ruins, Leo Kessler a young American of German descent feels obliged to help in their restoration. It is not a simple task as he quickly finds out.<br /><br />His uncle finds him a job as a night conductor on the Zentropa Railway Line. His job is to attend to the needs of the passengers. When the shoes are polished a chalk mark is made on the soles. A terrible argument ensues when a passenger's shoes are not chalked despite the fact they have been polished. There are many allusions to the German fanaticism of adherence to such stupid details.<br /><br />The railway journey is like an allegory representing man's procession through life with all its trials and tribulations. In one sequence Leo dashes through the back carriages to discover them filled with half-starv

In [6]:
# We can see the raw text data contains html script
# So we need to remove html element and clean the data using html.parser from BeautifulSoup

from bs4 import BeautifulSoup
#  remove http format and clean text
soup = BeautifulSoup(review, "html.parser")
review = soup.get_text()
review

"Lars Von Trier is never backward in trying out new techniques. Some of them are very original while others are best forgotten.He depicts postwar Germany as a nightmarish train journey. With so many cities lying in ruins, Leo Kessler a young American of German descent feels obliged to help in their restoration. It is not a simple task as he quickly finds out.His uncle finds him a job as a night conductor on the Zentropa Railway Line. His job is to attend to the needs of the passengers. When the shoes are polished a chalk mark is made on the soles. A terrible argument ensues when a passenger's shoes are not chalked despite the fact they have been polished. There are many allusions to the German fanaticism of adherence to such stupid details.The railway journey is like an allegory representing man's procession through life with all its trials and tribulations. In one sequence Leo dashes through the back carriages to discover them filled with half-starved bodies appearing to have just esc

In [7]:
# Use re regular equation to convert text to lower case
import re
review = re.sub('\[[^]]*\]', ' ', review)
review = re.sub('[^a-zA-Z]', ' ', review)
review = review.lower()
review

'lars von trier is never backward in trying out new techniques  some of them are very original while others are best forgotten he depicts postwar germany as a nightmarish train journey  with so many cities lying in ruins  leo kessler a young american of german descent feels obliged to help in their restoration  it is not a simple task as he quickly finds out his uncle finds him a job as a night conductor on the zentropa railway line  his job is to attend to the needs of the passengers  when the shoes are polished a chalk mark is made on the soles  a terrible argument ensues when a passenger s shoes are not chalked despite the fact they have been polished  there are many allusions to the german fanaticism of adherence to such stupid details the railway journey is like an allegory representing man s procession through life with all its trials and tribulations  in one sequence leo dashes through the back carriages to discover them filled with half starved bodies appearing to have just esc

In [8]:
review = review.split()
review

['lars',
 'von',
 'trier',
 'is',
 'never',
 'backward',
 'in',
 'trying',
 'out',
 'new',
 'techniques',
 'some',
 'of',
 'them',
 'are',
 'very',
 'original',
 'while',
 'others',
 'are',
 'best',
 'forgotten',
 'he',
 'depicts',
 'postwar',
 'germany',
 'as',
 'a',
 'nightmarish',
 'train',
 'journey',
 'with',
 'so',
 'many',
 'cities',
 'lying',
 'in',
 'ruins',
 'leo',
 'kessler',
 'a',
 'young',
 'american',
 'of',
 'german',
 'descent',
 'feels',
 'obliged',
 'to',
 'help',
 'in',
 'their',
 'restoration',
 'it',
 'is',
 'not',
 'a',
 'simple',
 'task',
 'as',
 'he',
 'quickly',
 'finds',
 'out',
 'his',
 'uncle',
 'finds',
 'him',
 'a',
 'job',
 'as',
 'a',
 'night',
 'conductor',
 'on',
 'the',
 'zentropa',
 'railway',
 'line',
 'his',
 'job',
 'is',
 'to',
 'attend',
 'to',
 'the',
 'needs',
 'of',
 'the',
 'passengers',
 'when',
 'the',
 'shoes',
 'are',
 'polished',
 'a',
 'chalk',
 'mark',
 'is',
 'made',
 'on',
 'the',
 'soles',
 'a',
 'terrible',
 'argument',
 'ensues',

In [9]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
#remove stop words here since stop words don't contain information related to sentiment / rating 
review = [word for word in review if not word in set(stopwords.words('english'))]
review

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/wenkanw/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['lars',
 'von',
 'trier',
 'never',
 'backward',
 'trying',
 'new',
 'techniques',
 'original',
 'others',
 'best',
 'forgotten',
 'depicts',
 'postwar',
 'germany',
 'nightmarish',
 'train',
 'journey',
 'many',
 'cities',
 'lying',
 'ruins',
 'leo',
 'kessler',
 'young',
 'american',
 'german',
 'descent',
 'feels',
 'obliged',
 'help',
 'restoration',
 'simple',
 'task',
 'quickly',
 'finds',
 'uncle',
 'finds',
 'job',
 'night',
 'conductor',
 'zentropa',
 'railway',
 'line',
 'job',
 'attend',
 'needs',
 'passengers',
 'shoes',
 'polished',
 'chalk',
 'mark',
 'made',
 'soles',
 'terrible',
 'argument',
 'ensues',
 'passenger',
 'shoes',
 'chalked',
 'despite',
 'fact',
 'polished',
 'many',
 'allusions',
 'german',
 'fanaticism',
 'adherence',
 'stupid',
 'details',
 'railway',
 'journey',
 'like',
 'allegory',
 'representing',
 'man',
 'procession',
 'life',
 'trials',
 'tribulations',
 'one',
 'sequence',
 'leo',
 'dashes',
 'back',
 'carriages',
 'discover',
 'filled',
 'half

In [10]:
from nltk.stem import WordNetLemmatizer
# lemmatizer words, re-form the distorted words

# if use stemmer, deannotate the following line. But Lemmatizer is better than stemmer
# from nltk.stem.porter import PorterStemmer
lem = WordNetLemmatizer()
review = [lem.lemmatize(word) for word in review]
review

['lars',
 'von',
 'trier',
 'never',
 'backward',
 'trying',
 'new',
 'technique',
 'original',
 'others',
 'best',
 'forgotten',
 'depicts',
 'postwar',
 'germany',
 'nightmarish',
 'train',
 'journey',
 'many',
 'city',
 'lying',
 'ruin',
 'leo',
 'kessler',
 'young',
 'american',
 'german',
 'descent',
 'feel',
 'obliged',
 'help',
 'restoration',
 'simple',
 'task',
 'quickly',
 'find',
 'uncle',
 'find',
 'job',
 'night',
 'conductor',
 'zentropa',
 'railway',
 'line',
 'job',
 'attend',
 'need',
 'passenger',
 'shoe',
 'polished',
 'chalk',
 'mark',
 'made',
 'sol',
 'terrible',
 'argument',
 'ensues',
 'passenger',
 'shoe',
 'chalked',
 'despite',
 'fact',
 'polished',
 'many',
 'allusion',
 'german',
 'fanaticism',
 'adherence',
 'stupid',
 'detail',
 'railway',
 'journey',
 'like',
 'allegory',
 'representing',
 'man',
 'procession',
 'life',
 'trial',
 'tribulation',
 'one',
 'sequence',
 'leo',
 'dash',
 'back',
 'carriage',
 'discover',
 'filled',
 'half',
 'starved',
 'bod

In [11]:
review = ' '.join(review)
review

'lars von trier never backward trying new technique original others best forgotten depicts postwar germany nightmarish train journey many city lying ruin leo kessler young american german descent feel obliged help restoration simple task quickly find uncle find job night conductor zentropa railway line job attend need passenger shoe polished chalk mark made sol terrible argument ensues passenger shoe chalked despite fact polished many allusion german fanaticism adherence stupid detail railway journey like allegory representing man procession life trial tribulation one sequence leo dash back carriage discover filled half starved body appearing escaped auschwitz image horrible fleeting dream terrible impact yet unconnected station called urmitz leo jump train parceled bomb view many stander connects bomb underside carriage return cabin make connection time clock later jump train high speed lie cool grass river bank looking star decides job build destroy subsequently see train approaching

In [12]:
corpus = []
corpus.append(review)

In [13]:
# test with count vector
from sklearn.feature_extraction.text import CountVectorizer
# count_vec= CountVectorizer(binary=True)  #convert count to binary 0 1 values
count_vec= CountVectorizer()
review_count_vec= count_vec.fit_transform(corpus)
review_count_vec.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
        1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
        1, 2, 1, 2, 1, 1, 3, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 1, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 6, 1, 1, 2, 1, 1, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 1]])

In [14]:
# Test with TFIDF vector
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer()
review_tfidf_vec = tfidf_vec.fit_transform(corpus)

review_tfidf_vec.toarray()

array([[0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.1726306 , 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.11508707, 0.05754353, 0.05754353, 0.05754353,
        0.11508707, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.11508707, 0.05754353,
        0.11508707, 0.05754353, 0.11508707, 0.05754353, 0.05754353,
        0.1726306 , 0.05754353, 0.05754353, 0.05754353, 0.11508707,
        0.11508707, 0.05754353, 0.05754353, 0.11508707, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.05754353, 0.05754353,
        0.05754353, 0.05754353, 0.05754353, 0.17

In [103]:
from sklearn.model_selection import train_test_split

dataset_train = dataset['text']
train_data_label = dataset['label']
testdata = pd.read_csv("../aclImdb/test.csv")
dataset_test= testdata['text']
test_data_label = testdata['label']


In [104]:
test_data_label.shape, train_data_label.shape, 

((25000,), (25000,))

In [106]:
dataset_test.iloc[0]

"Previous reviewer Claudio Carvalho gave a much better recap of the film's plot details than I could. What I recall mostly is that it was just so beautiful, in every sense - emotionally, visually, editorially - just gorgeous.<br /><br />If you like movies that are wonderful to look at, and also have emotional content to which that beauty is relevant, I think you will be glad to have seen this extraordinary and unusual work of art.<br /><br />On a scale of 1 to 10, I'd give it about an 8.75. The only reason I shy away from 9 is that it is a mood piece. If you are in the mood for a really artistic, very romantic film, then it's a 10. I definitely think it's a must-see, but none of us can be in that mood all the time, so, overall, 8.75."

In [107]:
dataset_train.iloc[0]

'Zentropa has much in common with The Third Man, another noir-like film set among the rubble of postwar Europe. Like TTM, there is much inventive camera work. There is an innocent American who gets emotionally involved with a woman he doesn\'t really understand, and whose naivety is all the more striking in contrast with the natives.<br /><br />But I\'d have to say that The Third Man has a more well-crafted storyline. Zentropa is a bit disjointed in this respect. Perhaps this is intentional: it is presented as a dream/nightmare, and making it too coherent would spoil the effect. <br /><br />This movie is unrelentingly grim--"noir" in more than one sense; one never sees the sun shine. Grim, but intriguing, and frightening.'

In [9]:
testdata = pd.read_csv("../aclImdb/test.csv")
dataset_test= testdata['text']
test_data_label = testdata['label']

### Clean text here
Since there are some text in html format and some distorted text, we need to clean and restore text by using BeautifulSoup(clean html text)  and NLTK,Lemmatizer (restore text)

In [62]:
from bs4 import BeautifulSoup
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
def clean_data(dataset):
    corpus_data= []
    for i in range(dataset.shape[0]):
        soup = BeautifulSoup(dataset.iloc[i], "html.parser")
        review = soup.get_text()
        review = re.sub('\[[^]]*\]', ' ', review)
        review = re.sub('[^a-zA-Z]', ' ', review)
        review = review.lower()
        review = review.split()
        # remove stopwords
        review = [word for word in review if not word in set(stopwords.words('english'))]
        # lemmatize the distorted words
        lem = WordNetLemmatizer()
        review = [lem.lemmatize(word) for word in review]
        review = ' '.join(review)
        # cleaned text data
        corpus_data.append(review)
    return corpus_data


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/wenkanw/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
# corpus_train = clean_data(dataset_train)
# corpus_test = clean_data(dataset_test)

In [18]:
corpus_test[0]

'previous reviewer claudio carvalho gave much better recap film plot detail could recall mostly beautiful every sense emotionally visually editorially gorgeous like movie wonderful look also emotional content beauty relevant think glad seen extraordinary unusual work art scale give reason shy away mood piece mood really artistic romantic film definitely think must see none u mood time overall'

In [19]:
import csv
def save_clean_data(train_txt, train_label,train_score, test_txt,test_label,test_score):
    fp = open("cleaned_train.csv","w+")
    fieldnames = ["text","label","score"]
    writer = csv.DictWriter(fp, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(len(train_txt)):
        writer.writerow({'text': train_txt[i], 'label': train_label[i],'score':train_score[i]})
    fp.close()
    
    test_fp = open("cleaned_test.csv","w+")
    fieldnames = ["text","label","score"]
    writer = csv.DictWriter(test_fp, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(len(test_txt)):
        
        writer.writerow({'text': test_txt[i], 'label': test_label[i],'score':test_score[i]})
    test_fp.close()

def save_test_data( test_txt,test_label,test_score):
    test_fp = open("cleaned_test.csv","w+")
    fieldnames = ["text","label","score"]
    writer = csv.DictWriter(test_fp, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(len(test_txt)):
        writer.writerow({'text': test_txt[i], 'label': test_label[i],'score':test_score[i]})
    test_fp.close()

In [20]:
len(corpus_test)

25000

In [21]:
# save_test_data(corpus_test, testdata['label'],testdata['score'])

In [36]:
## save cleaned text data for future use
# save_clean_data(corpus_train,dataset['label'],dataset['score'],corpus_test, testdata['label'],testdata['score'])

### Load cleaned text data here 

In [22]:
# Load text dataset  that have been cleaned

clean_data = pd.read_csv("cleaned_train.csv")
clean_test = pd.read_csv("cleaned_test.csv")


In [23]:
corpus_test = clean_test['text']
corpus_train = clean_data['text']
len(clean_data),len(clean_test)

(25000, 25000)

In [24]:
clean_data['text'].iloc[-2]

'film begin cowhand shagging female calf promise much stereotyping kibbutz yr ago well like ok every kibbutz small piece something shown film like youngster raiding kitchen night show whole kibbutz full shall say naughty trait kibbutz problem hardly kibbutz view israel great still remember youth garden eden called emek valley yes acting good see black wrong portrayal probably purpose'

In [25]:
clean_test['text'].iloc[-2]

'wild rebel probably fun second film drive movie triple feature year ago aged well never meant age well obviously intended disposable forgettable fun inception taken level good example biker flick genre several element help distinguish dozen similar film churned time hero rod tillman steve alaimo come somewhat unimpressive everyman especially brave tough talented handsome although win fight tough biker gang member halfway film girl gang member chooses help fellow gang member end film soundtrack quite well done featuring nice venture style bass drum riff keep thing moving saxophone brass chart pep thing quite bit although script pretty shallow actor inhabit cardboard character convincingly fair amount energy plenty careless technical gaffe terrible day night scene occur broad daylight squealing tire swamp fire siren mistakenly stuck soundtrack instead police siren bank sign made duct tape ceiling tile luger sound like winchester shotgun blast cut people yard away detective killing biker

In [86]:
from numba import cuda
print(cuda.gpus)

<Managed Device 0>


### Tokenize and Vectorize 
Convert raw text to vector (like Bag-of-word model, word2vector, fasttext, Glove) to  visualize and analyze text data

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Using TFIDF
# n_gram: the number of char in a word
# if using n_gram=3, then in ["I Like dog so much"] sentence, it is broken into ["I like dog", "like dog so", "dog so much"]
# gram means the size of window that contains consecutive words

#Note: Tfidf vectorizer already normalize the data and avoid zero-division by setting flag:  smooth_idf=True
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))
tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

# Using count vectorizer
count_vec = CountVectorizer(ngram_range=(1, 3), binary=False)
count_vec_train = count_vec.fit_transform(corpus_train)
count_vec_test = count_vec.transform(corpus_test)

In [32]:

len(tfidf_vec_train.data),len(count_vec_train.data)
# la = np.linalg
# U,s, Vp = la.svd(count_vec_train,full_matrices=False)

(8202611, 8202611)

In [120]:
tfidf_vec_train.shape, tfidf_vec_test.shape

((25000, 4485967), (25000, 4485967))

In [35]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from sklearn.decomposition import PCA
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
# vaderSentiment: a lexicon and rule-based tool
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer 

### Simply Apply SentimentIntensityAnalyzer to see if it helps with classification of emotion

sentimentIntensityAnalyzer is a lexicon and rule-based sentiment analysis tool. It measures the polarity score based on vocabulary meaning. 

In [38]:

sentiment = clean_data.copy()
sia=  SentimentIntensityAnalyzer()
sentiment['polarity_score']=sentiment.text.apply(lambda x:sia.polarity_scores(x)['compound'])


In [50]:
# step: -1.0  -0.75, -0.5, -0.25,  0, 0.25,  0.5, 0.75,   1
#Rating:     1      2     3     4    7      8    9     10   
step=0.25
labels= [1,2,3,4,7,8,9,10]
for i in range(8):
    sentiment.loc[sentiment.polarity_score>=(step*i)-1.0,"Rating"]=labels[i]
sentiment[['score','polarity_score','Rating']]

score  polarity_score Rating
0          7         -0.0772      4
1         10          0.8715     10
2          7         -0.9839      1
3         10         -0.3472      3
4         10          0.9850     10
...      ...             ...    ...
24995      3         -0.0064      4
24996      1         -0.9854      1
24997      4          0.9789     10
24998      1          0.9260     10
24999      3          0.9491     10

[25000 rows x 3 columns]

In [55]:
# Accuracy when using SentimentIntensityAnalyzer
print("Accuracy:",len(sentiment.loc[sentiment.score==sentiment.Rating])/len(sentiment))

Accuracy: 0.25752


In [57]:
sentiment['text'].iloc[-2]

'film begin cowhand shagging female calf promise much stereotyping kibbutz yr ago well like ok every kibbutz small piece something shown film like youngster raiding kitchen night show whole kibbutz full shall say naughty trait kibbutz problem hardly kibbutz view israel great still remember youth garden eden called emek valley yes acting good see black wrong portrayal probably purpose'

In [60]:
dataset['text'].iloc[-2]

"Any film which begins with a cowhand shagging a female calf can't promise much. As for the stereotyping of the kibbutz as it was 50 yrs ago, well I was there and it just wasn't like that. OK every kibbutz had just a small piece of something shown in the film (like youngsters raiding the kitchen at night) but you can't show the whole kibbutz as being full of all those - shall we say - naughty traits. Each kibbutz had its own problems, but hardly any kibbutz had all of them. The views of Israel were great. I still remember my youth in that Garden of Eden called the Emek (valley). Yes, and the acting was good too, so you see it wasn't all black - just a wrong portrayal - probably on purpose too."

In [63]:
# stopwords.words('english')

not_words= ['don',
 "don't",
 'should',
 "should've",
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]
len(not_words)

38

### Analysis of using sentimentIntensityAnalyzer (SIA)
We can see the result is bad using SIA, possible reasons are following
1. It is based on words from dictionary and hence ignores the context of words
2. In text sentiment['text'].iloc[-2], we can see most of words are positive after removing stopwords.
However, when looking at the original text, we can see stopword ,like can't, shouldn't, ahead the positive texts are removed. __Then the meaning of text is actually reversed and distorted after removing some stopwords!__. 
This could be a reason why the rating =1, but the polarity score is 0.9->rating=10

### Use Word2Vector and PCA for dimension reduction

In [172]:
# Test with Word2Vec model for word vectors
from gensim.test.utils import common_texts
from gensim.models import Word2Vec
print(common_texts)
corpuses = corpus_train.copy()
corpuses += corpus_test
model = Word2Vec(corpuses, size=100, window=5, min_count=1, workers=4)
word_vectors = model.wv


[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]


AttributeError: 'Series' object has no attribute 'concate'

In [170]:
# load pre-trained word-vectors from gensim-data

# import gensim.downloader as api
# glove_word_vectors = api.load("glove-wiki-gigaword-100")  
# result = glove_word_vectors.most_similar(positive=['woman', 'king'], negative=['man'])
# print("{}: {:.4f}".format(*result[0]))


# result = word_vectors.most_similar(positive=['like', 'enjoy'], negative=['sad'])
# print("{}: {:.4f}".format(*result[0]))

lars von trier never backward trying new technique original others best forgotten depicts postwar germany nightmarish train journey many city lying ruin leo kessler young american german descent feel obliged help restoration simple task quickly find uncle find job night conductor zentropa railway line job attend need passenger shoe polished chalk mark made sol terrible argument ensues passenger shoe chalked despite fact polished many allusion german fanaticism adherence stupid detail railway journey like allegory representing man procession life trial tribulation one sequence leo dash back carriage discover filled half starved body appearing escaped auschwitz image horrible fleeting dream terrible impact yet unconnected station called urmitz leo jump train parceled bomb view many stander connects bomb underside carriage return cabin make connection time clock later jump train high speed lie cool grass river bank looking star decides job build destroy subsequently see train approaching 

In [99]:
import torch
data = [("me gusta comer en la cafeteria".split(), "SPANISH"),
        ("Give it to me".split(), "ENGLISH"),
        ("No creo que sea una buena idea".split(), "SPANISH"),
        ("No it is not a good idea to get lost at sea".split(), "ENGLISH")]

test_data = [("Yo creo que si".split(), "SPANISH"),
             ("it is lost on me".split(), "ENGLISH")]

# word_to_ix maps each word in the vocab to a unique integer, which will be its
# index into the Bag of words vector
word_to_ix = {}
for sent, _ in data + test_data:
    for word in sent:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)
print(word_to_ix)

VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2


class BoWClassifier(nn.Module):  # inheriting from nn.Module!

    def __init__(self, num_labels, vocab_size):
        # calls the init function of nn.Module.  Dont get confused by syntax,
        # just always do it in an nn.Module
        super(BoWClassifier, self).__init__()

        # Define the parameters that you will need.  In this case, we need A and b,
        # the parameters of the affine mapping.
        # Torch defines nn.Linear(), which provides the affine map.
        # Make sure you understand why the input dimension is vocab_size
        # and the output is num_labels!
        self.linear = nn.Linear(vocab_size, num_labels)

        # NOTE! The non-linearity log softmax does not have parameters! So we don't need
        # to worry about that here

    def forward(self, bow_vec):
        # Pass the input through the linear layer,
        # then pass that through log_softmax.
        # Many non-linearities and other functions are in torch.nn.functional
        return F.log_softmax(self.linear(bow_vec), dim=1)


def make_bow_vector(sentence, word_to_ix):
    vec = torch.zeros(len(word_to_ix))
    for word in sentence:
        vec[word_to_ix[word]] += 1
    return vec.view(1, -1)


def make_target(label, label_to_ix):
    return torch.LongTensor([label_to_ix[label]])


model = BoWClassifier(NUM_LABELS, VOCAB_SIZE)

# the model knows its parameters.  The first output below is A, the second is b.
# Whenever you assign a component to a class variable in the __init__ function
# of a module, which was done with the line
# self.linear = nn.Linear(...)
# Then through some Python magic from the PyTorch devs, your module
# (in this case, BoWClassifier) will store knowledge of the nn.Linear's parameters
for param in model.parameters():
    print(param)

# To run the model, pass in a BoW vector
# Here we don't need to train, so the code is wrapped in torch.no_grad()
with torch.no_grad():
    sample = data[0]
    bow_vector = make_bow_vector(sample[0], word_to_ix)
    log_probs = model(bow_vector)
    print(log_probs)

{'me': 0, 'gusta': 1, 'comer': 2, 'en': 3, 'la': 4, 'cafeteria': 5, 'Give': 6, 'it': 7, 'to': 8, 'No': 9, 'creo': 10, 'que': 11, 'sea': 12, 'una': 13, 'buena': 14, 'idea': 15, 'is': 16, 'not': 17, 'a': 18, 'good': 19, 'get': 20, 'lost': 21, 'at': 22, 'Yo': 23, 'si': 24, 'on': 25}
Parameter containing:
tensor([[ 0.0575, -0.1513,  0.1328,  0.1744, -0.0264,  0.1678, -0.1648, -0.0646,
         -0.1617, -0.1345,  0.1446, -0.1234, -0.0837, -0.1888, -0.0679, -0.0176,
          0.0958, -0.0148,  0.1158, -0.0202, -0.1049, -0.0290, -0.1068, -0.1386,
         -0.0886,  0.0586],
        [ 0.0372,  0.1108,  0.0497, -0.1885, -0.0363, -0.0570,  0.1852,  0.0322,
         -0.0567,  0.1407, -0.0993,  0.0212,  0.1664,  0.0115, -0.1285,  0.1217,
         -0.1870,  0.0233,  0.0737,  0.1719, -0.0487, -0.1668, -0.1702, -0.0219,
         -0.0996, -0.0599]], requires_grad=True)
Parameter containing:
tensor([0.0720, 0.0341], requires_grad=True)
tensor([[-0.4829, -0.9597]])


In [141]:
def save_vocab(vocab):
    import csv
    fp = open("vocab.csv","w+")
    fieldname= ["vocab"]
    writer = csv.DictWriter(fp, fieldnames= fieldname)
    writer.writeheader()
    for i in vocab:
        writer.writerow({"vocab":i})
    fp.close()
    
# compute vocabulary set
vocab =set()
for d in corpus_train:
    vocab = vocab | set(d.split(" "))
for d in corpus_test:
    vocab = vocab |  set(d.split(" "))

# save vocabulary 
save_vocab(vocab)


In [142]:
print(len(vocab))

91721


### Test with Word Embedding in pytorch
#### Note 1: Usage of Word embedding in Pytorch is similar with that of Tensorflow
 Usage:
  embed = Embedding(vocabulary_size, output_size, input_length)    # return an instance
  one_hot_vector = one_hot(word, vocabulary size)
  
  \# one_hot_vector here use index of word rather than 0,1 representation
  word_vector = embed(one_hot_vector)   


#### Note 2: 
     Since using word2vec, glove network to find word vector is a training process, 
     word embedding is actually a layer in the model you need to train.

In [139]:
# Test with Word Embedding in pytorch
# Note 1: Usage of Word embedding in Pytorch is similar with that of Tensorflow
# Usage:
#  embed = Embedding(vocabulary_size, output_size, input_length)    # return an instance
#  one_hot_vector = one_hot(word, vocabulary size)
#  word_vector = embed(one_hot_vector)   # one_hot_vector here use index of word rather than 0,1 representation


# Note 2: 
#     Since using word2vec, glove network to find word vector is a training process, 
#     word embedding is actually a layer in the model you need to train.
vocab = list(vocab)

vocab_size=len(vocab)
word_to_ix = [one_hot(d, vocab_size) for d in corpus_train]
# 这里的2表示有2个词，5表示5维，其实也就是一个2×5的矩阵，所以如果你有1000个词，每个词希望是100维，你就可以这样建立一个word embedding，nn.Embedding(1000, 100)
# embeds = torch.nn.Embedding(2, 5)

embeds = torch.nn.Embedding(vocab_size, 1000)
word_idx = torch.LongTensor([vocab.index('remedy')])
print(word_idx)
word_embed = embeds(word_idx)
print(word_embed)
print("Vector len:",len(word_embed[0]))


tensor([4])
tensor([[ 1.0892e+00,  1.2696e+00, -1.9310e-01,  3.5289e-01,  2.7012e-01,
         -9.7955e-01, -1.2013e+00,  2.2520e-01, -2.7349e+00,  4.3028e-01,
         -1.0089e-01,  5.5109e-01,  2.0240e-02, -2.9043e-01, -2.7021e-01,
         -9.8227e-01,  1.7570e+00, -1.6500e+00,  1.0137e-01, -2.1284e-01,
         -1.2893e-01,  1.1705e+00, -7.7892e-01, -1.5826e+00,  2.7917e-01,
          1.6468e+00, -5.7773e-01,  4.2946e-01,  7.0890e-01,  7.3952e-01,
         -7.3561e-01, -1.0517e+00, -9.0542e-01,  1.4862e+00, -1.2152e+00,
          8.0583e-02, -5.6066e-01, -6.4583e-01,  2.6959e-01, -1.0710e+00,
          1.2237e+00,  4.9748e-01, -1.2456e+00, -2.1904e+00,  1.5265e-01,
         -1.9129e+00,  7.5209e-01,  2.5391e+00,  2.0054e+00,  4.7732e-01,
         -6.5085e-01,  1.2591e+00,  6.3316e-01,  1.9343e+00, -8.0991e-01,
         -1.2683e+00, -2.4974e-01, -1.5831e+00, -8.0501e-01,  2.7258e-01,
          6.6800e-01, -1.0592e+00, -9.1319e-01,  7.0144e-01,  2.1859e-02,
         -7.5321e-01, -6.4

In [77]:
import keras.layers as layers 
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [97]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [143]:
from numpy import array
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[42, 38], [3, 40], [7, 36], [40, 40], [12], [35], [28, 36], [39, 3], [28, 40], [36, 26, 38, 15]]
[[42 38  0  0]
 [ 3 40  0  0]
 [ 7 36  0  0]
 [40 40  0  0]
 [12  0  0  0]
 [35  0  0  0]
 [28 36  0  0]
 [39  3  0  0]
 [28 40  0  0]
 [36 26 38 15]]


InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

In [93]:
#define deep neural network with embeddings
max_length = 4
input_shape = count_vec_train.shape[1]
output_shape = 64
# padded_docs = pad_sequences(count_vec_train.shape[0], maxlen=max_length, padding='post')
model = Sequential()
model.add(Embedding(input_shape, output_shape, input_length=128 ))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(layers.Dropout())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='categories_crossentropy', metrics=['accuracy'])
print(model.summary())
# fit the model
# padded_docs
model.fit(count_vec_train, clean_data['score'], epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(count_vec_train, clean_data['score'], verbose=0)
print('Accuracy: %f' % (accuracy*100))



InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

RuntimeError: index out of range: Tried to access index 4485967 out of table with 4485966 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

In [137]:
# label types: rating from 1 to 10
target_names = set(dataset['score'])
target_names= list(target_names)
target_names

[1, 2, 3, 4, 7, 8, 9, 10]

In [203]:
from sklearn.svm import LinearSVC
clf = LinearSVC(C=0.1, random_state=40).fit(tfidf_vec_train, dataset['score'])
#train corpus score
clf.score(tfidf_vec_train, dataset['score'])

0.91048

In [204]:
# clf.score(tfidf_vec_test, testdata['score'])
test_label = testdata['score']
pred = clf.predict(tfidf_vec_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(test_label, pred,  labels = target_names))
print("Accuracy: \n", accuracy_score(testdata['score'], pred))

              precision    recall  f1-score   support

           1       0.39      0.51      0.44      5022
           2       0.19      0.13      0.16      2302
           3       0.19      0.16      0.17      2541
           4       0.23      0.21      0.22      2635
           7       0.19      0.18      0.19      2307
           8       0.23      0.23      0.23      2850
           9       0.19      0.15      0.17      2344
          10       0.40      0.44      0.42      4999

    accuracy                           0.30     25000
   macro avg       0.25      0.25      0.25     25000
weighted avg       0.28      0.30      0.29     25000

Accuracy: 
 0.29736


In [145]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression( solver = 'sag', random_state=0).fit(tfidf_vec_train, dataset['score'])
#train corpus score
lr_clf.score(tfidf_vec_train, dataset['score'])

0.90388

In [182]:
test_label = testdata['score']
lr_pred = lr_clf.predict(tfidf_vec_test)
print(classification_report(test_label, lr_pred,  labels = target_names))
print("Accuracy: \n", accuracy_score(testdata['score'], lr_pred))

              precision    recall  f1-score   support

           1       0.39      0.50      0.44      5022
           2       0.19      0.13      0.15      2302
           3       0.19      0.15      0.17      2541
           4       0.22      0.21      0.22      2635
           7       0.19      0.18      0.18      2307
           8       0.23      0.23      0.23      2850
           9       0.19      0.14      0.16      2344
          10       0.39      0.45      0.42      4999

    accuracy                           0.30     25000
   macro avg       0.25      0.25      0.25     25000
weighted avg       0.28      0.30      0.28     25000

Accuracy: 
 0.29512


In [189]:
from sklearn.svm import LinearSVC 
svc_clf = LinearSVC(C=0.05).fit(tfidf_vec_train, dataset['score'])
svc_clf.score(tfidf_vec_train, dataset['score'])

0.68652

In [206]:
svc_pred = svc_clf.predict(tfidf_vec_test)
test_label = testdata['score']
print(classification_report(test_label, svc_pred,  labels = target_names))
print("Accuracy: \n", accuracy_score(testdata['score'], svc_pred))

              precision    recall  f1-score   support

           1       0.38      0.70      0.49      5022
           2       0.18      0.04      0.06      2302
           3       0.19      0.07      0.10      2541
           4       0.23      0.15      0.18      2635
           7       0.19      0.14      0.16      2307
           8       0.24      0.18      0.21      2850
           9       0.20      0.05      0.08      2344
          10       0.37      0.61      0.46      4999

    accuracy                           0.33     25000
   macro avg       0.25      0.24      0.22     25000
weighted avg       0.27      0.33      0.27     25000

Accuracy: 
 0.32632
